steps:

# Build Artifacts
- name: "python:3"
  entrypoint: 'mkdir'
  args: ["-p", "lorgs/static/_generated"]
  waitFor: ['-']

- name: "python:3"
  id: install_build_reqs
  entrypoint: python3
  args: ["-m", "pip", "install", "-t", "/workspace/lib", "pysass", "jsmin"]

- name: "python:3"
  entrypoint: python3
  args: ["-m", "pysassc", "--style=compact", "lorgs/templates/scss/main.scss", "lorgs/static/_generated/style.css"]
  env: ["PYTHONPATH=/workspace/lib"]
  waitFor:
  - install_build_reqs

- name: "python:3"
  entrypoint: python3
  args: ["scripts/minify.py"]
  env: ["PYTHONPATH=/workspace/lib"]
  waitFor:
  - install_build_reqs


# add config
- name: 'gcr.io/cloud-builders/gsutil'
  args: ["cp", "gs://lorgs-config/deploy_variables.yaml", '.']
  waitFor: ['-']  # The '-' indicates that this step begins immediately.


# Deploy the APP
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
  timeout: "1600s"
