
## find a way to share config with the main cloudbuild.yaml

steps:

# Build SCSS
- name: "python:3"
  entrypoint: python3
  args: ["-m", "pip", "install", "-t", ".", "pysass"]
- name: "python:3"
  entrypoint: 'mkdir'
  args: ["-p", "lorgs/static/_generated"]
- name: 'python:3'
  entrypoint: python3
  args: ["-m", "pysassc", "--style=compact", "lorgs/templates/scss/main.scss", "lorgs/static/_generated/style.css"]

# add sensible config
- name: 'gcr.io/cloud-builders/gsutil'
  args: ["cp", "gs://lorgs-config/deploy_variables.yaml", '.']
  waitFor: ['-']  # The '-' indicates that this step begins immediately.

# Deploy the APP
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy", "--no-promote"]  # <-- the only thing that is meant to differ from the main file
  timeout: "1600s"
