
[tool.isort]
line_length = 120
atomic = true
lines_after_imports = 2
profile = "black"


[tool.mypy]
exclude = ["venv"]
show_error_codes = true
# all strict flags
# strict = true
# warn_unused_configs = true
# disallow_any_generics = true
disallow_subclassing_any = false
disallow_untyped_calls = true
# disallow_untyped_defs = true
# disallow_incomplete_defs = true
check_untyped_defs = true
# disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
# no_implicit_reexport = true
# strict_equality = true
# strict_concatenate = true


[[tool.mypy.overrides]]
module = "arrow"
ignore_missing_imports = true


[[tool.mypy.overrides]]
module = "blinker"
ignore_missing_imports = true
