app: lorrgs
service: lorrgs-api
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  region: eu-west-1
  stage: ${opt:stage, "dev"}
  runtime: python3.8

  deploymentBucket:
    name: lorrgs-serverless-deployments

################################################################################
# package:
package:
  individually: true # package each module (eg.: "backend") individually
  patterns:
    - "!*/**"
    # - "lorgs/**"
    # - google_creds.json

plugins:
  # - serverless-python-requirements
  - serverless-layers
  - serverless-deployment-bucket


custom:
#   # pythonRequirements:
#   #   layer: true
  serverless-layers:
    - main_layer:
        functions:
          - main
        dependenciesPath: ./requirements.txt
    - auth_layer:
        functions:
          - auth

#   ####################################
#   # Custom Config
#   config:
#     LORGS_CONFIG_NAME: ${opt:LORGS_CONFIG_NAME, lorgs.config.ProductionConfig}
#     SECRET_KEY: ${opt:SECRET_KEY}
#     # Third Party Credentials
#     MONGO_URI: ${opt:MONGO_URI}
#     WCL_CLIENT_ID: ${opt:WCL_CLIENT_ID}
#     WCL_CLIENT_SECRET: ${opt:WCL_CLIENT_SECRET}
#     # Discord Auth
#     DISCORD_CLIENT_ID: ${opt:DISCORD_CLIENT_ID}
#     DISCORD_CLIENT_SECRET: ${opt:DISCORD_CLIENT_SECRET}
#     DISCORD_BOT_TOKEN: ${opt:DISCORD_BOT_TOKEN}


functions:
  main:  # main function for "all" endpoints
    runtime: python3.8
    memorySize: 128 # optional, in MB, default is 1024
    timeout: 6 # optional, in seconds, default is 6
    # module: lorgs
    handler: lorgs.app.create_handler
    environment:
      LORGS_CONFIG_NAME: lorgs.config.ProductionConfig
      SECRET_KEY: ${env:SECRET_KEY}

      # Third Party Credentials
      MONGO_URI: ${env:MONGO_URI}
      # WCL_CLIENT_ID: ${opt:WCL_CLIENT_ID}
      # WCL_CLIENT_SECRET: ${opt:WCL_CLIENT_SECRET}

      # DISCORD_CLIENT_ID: ${opt:DISCORD_CLIENT_ID}
      # DISCORD_CLIENT_SECRET: ${opt:DISCORD_CLIENT_SECRET}
      # DISCORD_BOT_TOKEN: ${opt:DISCORD_BOT_TOKEN}
      GOOGLE_APPLICATION_CREDENTIALS: "./google_creds.json"
    events:
      - http: GET /
      - http: GET /{proxy+}
    # layers:
    #   - Ref: PythonRequirementsLambdaLayer
    package:
      patterns:
        - "lorgs/**"


  auth:
    runtime: python3.8
    memorySize: 128 # optional, in MB, default is 1024
    timeout: 6 # optional, in seconds, default is 6
    handler: lorrgs_auth.handler.create_handler
    package:
      patterns:
        - "lorrgs_auth/**"
    events:
      - http: GET /auth/{proxy+}
