# Circle CI Config


version: 2.1


################################################################################
#
# Orbs
#
################################################################################


orbs:
  discord: antonioned/discord@0.1.0
  sonarcloud: sonarsource/sonarcloud@1.0.1


################################################################################
#
# Jobs
#
################################################################################

jobs:

  ################################
  # prep
  #
  build:
    docker:
      - image: cimg/node:16.9

    steps:
      # git checkout the code
      - checkout

      - run: npm install
      - run: npm run build
      - run: npm run format_app_yaml

      # move index page up, to simplfy routing
      - run: mv static/index.html .
      - run: mv static/robots.txt .

      # save build dir
      - persist_to_workspace:
          root: ~/
          paths:
            - project

  ################################
  # prep
  #
  sonarscan:
    docker:
      - image: cimg/node:16.9
    steps:
      - checkout
      - sonarcloud/scan

  ################################
  # deploy job
  #

  deploy:

    parameters:
      promote:
        description: promote the deployed service to be the new default
        type: boolean
        default: false

      version:
        # Note: May only contain lowercase letters, digits, and hyphens. Must begin and end with a letter or digit. Must not exceed 63 characters.
        description: version name for the App Engine Deploy
        type: string
        default: dev

    docker:
      - image: google/cloud-sdk:alpine

    steps:

      # load the files build from webpack
      - attach_workspace:
          at: ~/

      ####################################
      # commands to execute the final deployment to google app engine
      #
      # 1) copy google service account login data
      - run:
          name: setup google service account
          command: |
            echo ${GOOGLE_CREDS} > /tmp/google_key.json
            gcloud auth activate-service-account --key-file=/tmp/google_key.json
            rm /tmp/google_key.json

      # 2) deploy the app engine
      - run:
          name: Deploy to AppEngine
          command: >
            gcloud --quiet app deploy
            --project lorrgs
            --version=<< parameters.version >>
            <<^ parameters.promote >> --no-promote<</ parameters.promote >>

      # 3) deploy the cloud functions
      # Note: this does not have a promote yes/no flag
      - run:
          name: Deploy Cloud Funtions
          command: ./scripts/deploy_functions

      ####################################
      # Discrd Notification
      #
      - discord/status:
          success_message: "new version deployed!!!"
          failure_message: "**${CIRCLE_USERNAME}**'s build: **${CIRCLE_JOB}** failed."
          webhook: "${DISCORD_WEBHOOK_URL}"


################################################################################
#
# Workflows
#
################################################################################


workflows:
  build-and-deploy:
    jobs:

      # always execute "build"
      - build

      - sonarscan

      # deploy for /master
      - deploy:
          promote: true
          version: v0-3-0
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - user_report_fixes

      # deploy for /devlop and similar branches
      - deploy:
          promote: false

          requires:
            - build

          filters:
            branches:
              only:
                - develop
