#!/usr/bin/env bash

shopt -s globstar

folders="./frontend/public/img"
extensions=".jpg .png"


# looks ulgy.. but works
for folder in $folders; do
    for ext in $extensions; do
        for file in $folder/**/*$ext; do
            ffmpeg -y -i $file -preset icon ${file%.*}.webp
        done # file
    done # ext
done # folders
