#!/usr/bin/env bash


############
# Settings

project_name=lorgs


# vars
# venv_root=~/.envs
# venv_dir=$venv_root/$project_name
venv_dir=./venv


################################################################################

# create and source virtualenv
if [ ! -d "$venv_dir" ]
then
    echo "creating virtualenv: ${venv_dir}"
    python3.11 -m venv venv
fi
source $venv_dir/bin/activate

# install requirements
pip install -U -r requirements.txt
pip install -U -r requirements_dev.txt
