#!/usr/bin/env bash

#
# Make sure the installed version is 3.9,
# which is currently the latest supported version in AWS Lambda
#
# >>> sudo apt-get update
# >>> sudo apt-get install python3.9 python3.9-venv
#

############
# Settings

project_name=lorgs


# vars
# venv_root=~/.envs
# venv_dir=$venv_root/$project_name
venv_dir=./venv


################################################################################

# create and source virtualenv
if [ ! -d "$venv_dir" ]
then
    echo "creating virtualenv: ${venv_dir}"
    python3.9 -m venv venv
fi
source $venv_dir/bin/activate

# install requirements
pip install -U -r requirements.txt
pip install -U -r requirements_dev.txt
