#!/usr/bin/env bash

echo "sourcing .env"
set -a
source .env
set +a


# env
if [ "$VIRTUAL_ENV" = "" ]
then
    source ./venv/bin/activate
fi
export PYTHONPATH=.  # adds current dir, so we can import


pytest -vv --cov lorgs/models test/test_models
