#!/usr/bin/env bash


# for the SONAR_TOKEN
echo "sourcing .env"
set -a
source .env
set +a


export SONAR_ROOT="/mnt/d/software/sonar/sonar-scanner-4.4.0.2170-linux"
$SONAR_ROOT/bin/sonar-scanner

