#!/usr/bin/env bash

echo "sourcing .env"
set -a
source .env
set +a


export FLASK_ENV=development
export QUART_ENV=$FLASK_ENV
export LORGS_CONFIG_NAME=lorgs.config.DevelopmentConfig

export PORT=5012
export FLASK_APP="lorgs/app:create_app()"
export QUART_APP=$FLASK_APP


export PYTHONPATH=.  # adds current dir, so we can import


# Dev Servers
# flask run --host=0.0.0.0 --port=$PORT --without-threads
quart run --host=0.0.0.0 --port=$PORT

# Prod Commands
# gunicorn -b :$PORT --timeout=240 "lorgs.app:create_app()" --workers 1
# hypercorn -b :$PORT "lorgs.app:create_app()" --workers 4
