#!/usr/bin/env bash


echo "sourcing .env"
set -a
source .env
set +a


REDISCLOUD_URL="redis://localhost:6379/0"

export PYTHONPATH=.  # adds current dir, so we can import
flower --app=lorgs.tasks.celery  --port=5555 --broker=$REDISCLOUD_URL

