name: Deploy

on:
  push:
    branches:
      - master
      - aws

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: NPM Install
        run: npm ci --ignore-scripts

      - name: Build
        run: npm run build

      - name: Serverless Authentication
        run: npx serverless config credentials --provider aws --key ${{secrets.AWS_ACCESS_KEY_ID}} --secret ${{secrets.AWS_SECRET_ACCESS_KEY}}

      - name: serverless deploy
        run: npx serverless deploy --verbose --stage ${GITHUB_REF##*/}
